# Generated by Django 4.1.1 on 2022-11-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dwitter", "0003_comment_comment_dwitter_com_created_542790_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="img",
            field=models.CharField(
                default="211-2112351_green-twitter-icon.png", max_length=40
            ),
        ),
    ]
